language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
matrix:
  allow_failures:
    - python: 3.3
install:
  - pip install -e git+git://github.com/django/django.git@${DJANGO_VERSION}#egg=django
  - pip install -r requirements.txt --use-mirrors
script: python setup.py test
